
name: CI workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: To Be Removed
        run: printenv

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: maven-central # Value of <id> in <server> section of generated settings.xml
          server-username: MAVEN_CENTRAL_USERNAME # env variable for username in <server> section of generated settings.xml
          server-password: MAVEN_CENTRAL_PASSWORD # env variable for password in <server> section of generated settings.xml
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Maven execution
        run: .github/scripts/maven-execution.sh
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}